name: ci

on: [pull_request]

jobs:

  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Check out 
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Set up npm local
      run: |
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        echo "::set-env name=PATH::~/.npm-global/bin:$PATH"
        echo "::set-env name=NODE_PATH::~/.npm-global/lib/node_modules:$NODE_PATH"
    - name: Verify links
      run: ./hack/verify-links.sh
    - name: Verify link anchors
      run: ./hack/verify-link-anchors.sh
    - name: Markdown lint
      uses: avto-dev/markdown-lint@v1
      with:
        config: './.markdownlint.yaml'
        args: '.'
